services:
  - type: web
    name: familiadoc
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DATABASE_URL
        fromDatabase:
          name: familiadoc-db
          property: connectionString

      # Optionnel : stockage S3 / Supabase
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        value: "eu-west-1"

databases:
  - name: familiadoc-db
    databaseName: familiadoc
    user: familiadoc
